2 вопрос
Задан двухмерный массив ar1 размерности (25,4), состоящий из случайных целых чисел в пределах от 0 до 15. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке(вывести индексы этих столбцов на экран с соответствующим комментарием)
Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек.

In [ ]:
import pandas
import numpy as np

In [ ]:
ar1 = np.random.randint(low=0, high=16, size=(25, 4))
ar1

array([[ 9,  9, 13, 14],
       [ 6,  4,  6,  0],
       [14,  3, 11, 11],
       [13,  2,  5, 13],
       [14, 13,  7,  0],
       [10,  7, 14, 12],
       [ 3,  1, 12, 13],
       [ 0,  1,  7,  9],
       [ 0,  4,  8,  4],
       [12,  0,  5,  9],
       [ 8, 13,  4,  7],
       [ 2,  4, 10, 10],
       [ 7, 11, 14,  0],
       [ 1,  3, 10,  1],
       [10,  8,  8,  3],
       [ 5, 11,  6,  7],
       [ 3,  6, 11,  1],
       [ 3,  4, 10,  6],
       [12, 13,  4,  2],
       [ 1,  7, 13,  6],
       [ 4, 14,  3,  6],
       [10,  6, 13, 11],
       [12, 12, 12,  3],
       [ 2,  2,  6, 14],
       [10,  0,  2, 12]])

In [ ]:
max_in_rows = ar1.max(axis=1)
max_in_rows

array([14,  6, 14, 13, 14, 14, 13,  9,  8, 12, 13, 10, 14, 10, 10, 11, 11,
       10, 13, 13, 14, 13, 12, 14, 12])

In [ ]:
count_max_in_cols = (ar1 == max_in_rows.reshape(-1, 1)).sum(axis=0)
count_max_in_cols

array([ 7,  5, 11,  7])

In [ ]:
print(f'Индексы столбцов, которые не менее 5 раз встречается значение максимальное по своей строке {list(np.where(count_max_in_cols >= 5)[0])}')

Индексы столбцов, которые не менее 5 раз встречается значение максимальное по своей строке [0, 1, 2, 3]


3 Вопрос Необходимо найти все целые числа от 1 до 400_000, для которых sin от этого числа будет иметь не менее 9 одинаковых цифр(например sin(139198)=0.30763333543133703 т.е. имеет 9 троек). Ответ представляет собой список пар(целое число, значение синуса для него), для которых значение синуса удовлетворяет условию.
Решение этой задачи распараллелить, используя multiprocessing Pool. Сравнить продолжительность последовательного и параллельного решения задачи

In [ ]:
%%time
#Последовательное решение задачи
import math

result = []

for num in range(1, 400_001):
    sine = str(math.sin(num))
    for char in sine:
        if sine.count(char) >= 9:
            result.append((num, float(sine)))
            break
            
print(result)

[(1797, 0.009002025051800673), (7089, 0.9999926930119999), (10639, 0.9999937999413936), (24074, 0.024502006300003643), (25904, -0.9999975242999319), (31249, 0.4097000800060077), (36693, -0.7188828881448883), (38968, -0.31007805001001504), (46617, 0.8881880887188651), (47105, -0.04023706000105806), (47306, -0.10200005360030799), (48979, 0.9999999646773939), (50399, 0.9999999894564097), (50754, -0.9999999933794586), (51109, 0.9999999963938254), (51464, -0.9999999984995102), (51819, 0.999999999696513), (52174, -0.9999999999848337), (52529, 0.9999999993644724), (52884, -0.999999997835429), (53239, 0.9999999953977037), (53594, -0.9999999920512962), (54609, 0.9649091969997949), (54659, 0.9999999765599817), (55724, -0.9999999528905291), (58564, -0.9999998497899818), (60694, -0.999999734299931), (63525, 0.9107300260000201), (66374, -0.9999992663984799), (67490, 0.7412811211116511), (78444, -0.9999974997289492), (97284, 0.9917029415999999), (102540, -0.9999099954979505), (106112, 0.999990909269

In [ ]:
num_lists = [[i for i in range(1, 100_001)],[i for i in range(100_001, 200_001)],[i for i in range(200_001, 300_001)],[i for i in range(300_001, 400_001)]]
len(num_lists[0]),len(num_lists[1]),len(num_lists[2]),len(num_lists[3])

(100000, 100000, 100000, 100000)

In [ ]:
%%file func1.py

import math

def func(num_list):
    result = []
    for number in num_list:
        sine = str(math.sin(number))
        for char in sine:
            if sine.count(char) >= 9:
                result.append((number, float(sine)))
                break
    return result

Overwriting func1.py


In [ ]:
from func1 import func

In [ ]:
%%time

import multiprocessing

with multiprocessing.Pool(processes = 4) as pool:
    res = pool.map(func, num_lists)
res

NameError: ignored